
POINTLIST* getKillPointListOf3LineWithoutSplitPoint(GOMOKU* puzzle, POINTLIST* p3Line, int lineStoneType);
bool isEndPointToMakePointListWith4Line(GOMOKU* puzzle, POINTLIST* pointList, int x, int y, int putStoneType);
int numOfStoneOnTheBoard(GOMOKU* puzzle);
int numOfCertainTypeStoneOnTheBoard(GOMOKU* puzzle, int stoneType);
bool isEndPointToMakePointListWith3Line(GOMOKU* puzzle, POINTLIST* pointList, int x, int y, int putStoneType);
bool isAbleToBeInterruptedLine(GOMOKU* puzzle, POINTLIST* pLine, int lineStoneType, int minimumLength);
bool isAliveLinePoint(GOMOKU* puzzle, int x, int y, int lineStoneType, int minimumLength);
POINT* getPointToMakeFinalStyleWith4LineRecursive(GOMOKU* puzzle, int putStoneType);
POINT* getPointToMakeFinalStyleWith3LineRecursive(GOMOKU* puzzle, int putStoneType);
POINT* getPointToMakePointListWith4LineRecursieve(GOMOKU* puzzle, POINTLIST* pointList, int putStoneType);
POINT* getPointToMakePointListWith3LineRecursieve(GOMOKU* puzzle, POINTLIST* pointList, int putStoneType);
bool isPointToMakePointList(GOMOKU* puzzle, POINTLIST* pointList, int x, int y, int putStoneType, int minimumLength);
bool isPointToPrepareToMakeFinalStyleWith4Line(GOMOKU* puzzle, int x, int y, int putStoneType);
bool isPointToPrepareToMakeFinalStyleWith3Line(GOMOKU* puzzle, int x, int y, int putStoneType);
nt y_orientation, int lineStoneType);
POINT* getEndOfLineWithOffset(GOMOKU* puzzle, POINTLIST* line, int x_orientation, int y_orientation, int lineStoneType);
bool isSplitLine(POINTLIST* pLine);
POINTLIST* getLineAbleToMake4WithOrientation(GOMOKU* puzzle, int x, int y, int x_orientation, int y_orientation, int lineStoneType);
POINTLIST* getSplitLineWithOrientation(GOMOKU* puzzle, int x, int y, int x_orientation, int y_orientation, int lineStoneType);
POINTLIST* findSplit4Line(GOMOKU* puzzle, int x, int y, int lineStoneType);
POINTLIST* findSplit3Line(GOMOKU* puzzle, int x, int y, int lineStoneType);
POINTLIST* findLineAbleToMake4(GOMOKU* puzzle, int x, int y, int lineStoneType);
POINTLIST* findAliveSplitLine(GOMOKU* puzzle, int x, int y, int lineStoneType, int lineLength);
int compareXPoint(const POINTLIST** a, const POINTLIST** b);
int compareYPoint(const POINTLIST** a, const POINTLIST** b);
void sortLine(POINTLIST* pLine);
int maxSubOfTwoPoint(int x1, int y1, int x2, int y2);
POINT* getSplitPoint(POINTLIST* pLine);
VECTOR* getLineOrientationVector(POINTLIST* line);
bool isInTheBoard(int x, int y);
POINT* findBlankBesideLine(GOMOKU* puzzle, POINTLIST* pLine, int lineStoneType);
int numOfAlivePoint(GOMOKU* puzzle, POINTLIST* pLine, int lineStoneType);
POINTLIST* getBlankPointListBesideLine(GOMOKU* puzzle, POINTLIST* pLine, int lineStoneType);
POINT* findAlivePointBesideLine(GOMOKU* puzzle, POINTLIST* pLine, int lineStoneType);
int numOf2BlankPointListBesideLine(GOMOKU* puzzle, POINTLIST* pLine, int lineStoneType);
POINTLIST* get2BlankPointListBesideLine(GOMOKU* puzzle, POINTLIST* pLine, int lineStoneType);
POINT* getKillPointOf4Line(GOMOKU* puzzle, POINTLIST* p4Line, int lineStoneType);
POINT* getKillPointOf3Line(GOMOKU* puzzle, POINTLIST* p3Line, int lineStoneType);
POINT* findAlivePointOf2Line(GOMOKU* puzzle, POINTLIST* p2Line, int lineStoneType);
POINTLIST* getKillPointListOf3Line(GOMOKU* puzzle, POINTLIST* p3Line, int lineStoneType);
void putStone(GOMOKU* puzzle, int x, int y, int putStoneType);
int isBannedPoint(GOMOKU* puzzle, int x, int y, int putStoneType);
void oneStepBack(GOMOKU* puzzle, int removeStoneType);

POINT* getPointToMake5Line(GOMOKU* puzzle, int putStoneType);
int getOppositeStone(int stoneType);
POINT* getPointToKill4Line(GOMOKU* puzzle, int putStoneType);
POINT* getPointToMake4Line(GOMOKU* puzzle, int putStoneType);
POINT* getPointToKillAlive3Line(GOMOKU* puzzle, int putStoneType);

bool isAliveLine(GOMOKU* puzzle, POINTLIST* pLine, int lineStoneType, bool check2Line);
bool isFinalStylePoint(GOMOKU* puzzle, int x, int y, int killedStoneType, bool bAllow3x3);

POINT* getPointToKillFinalStyle(GOMOKU* puzzle, int putStoneType);
POINT* getPointToMake3Line(GOMOKU* puzzle, int putStoneType);
POINT* getPointToPrepareToMakeFinalStyleWith4Line(GOMOKU* puzzle, int putStoneType);
POINT* getPointToPrepareToMakeFinalStyleWith3Line(GOMOKU* puzzle, int putStoneType);
POINT* getPointToMakeFinalStyle(GOMOKU* puzzle, int putStoneType, bool bAllow3x3);
POINT* getPointToKillDead3Line(GOMOKU* puzzle, int putStoneType);
POINT* getPointWithoutThought(GOMOKU* puzzle);
POINT* getAIPutPoint(GOMOKU* puzzle, int putStoneType, bool* bAbleToWin, int AILevel);
bool letAIPutStone(GOMOKU* puzzle, int putStoneType, int AILevel);
POINT* getCenterPointOfTheBoard();
POINT* getPointAroundCenterWithMT();

